name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /home/ubuntu/ConveneSpace-

          git pull origin master

          chmod +x mvnw
          ./mvnw clean package -DskipTests

          sudo docker compose down
          sudo docker compose up -d --build
